name: PTR Data Sync
on:
  push:
    branches:
    - main
    - workflow/*
  workflow_dispatch:

jobs:
  export-to-json:
    name: Export to JSON
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          path: ./Data/systems/ptu
      - name: Install Foundry CLI
        run: npm install -g @foundryvtt/foundryvtt-cli 
      - name: Setup Foundry CLI
        run: |
          fvtt configure set dataPath ./
          fvtt configure set currentPackageType System
          fvtt configure set currentPackageId ptu
      - name: Export Feats Compendium
        run: fvtt package unpack feats
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ptr-data-jsons
          path: packs/**/*.json
          retention-days: 1
  commit-to-ptr-data:
    name: Commit to PTR-Data
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout PTR-Data Repository
        uses: actions/checkout@v4
        with:
          repository: pokemon-tabletop-reunited/PTR-Data
      - name: Load Artifacts
        uses: actions/download-artifact@v3
        with: 
          name: ptr-data-jsons
      - name: Commit Changes
        run: git commit -am "Github-Actions Data Sync"
      - name: Push changes
        run: git push
    
